config-version = 2

start-at-login = true

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

persistent-workspaces = ["1", "2", "3", "4", "5", "6"]

[gaps]
inner.horizontal = 0
inner.vertical = 0
outer.left = 0
outer.top = 0
outer.right = 0
outer.bottom = 0

[mode.main.binding]
ctrl-1 = 'workspace 1'
ctrl-2 = 'workspace 2'
ctrl-3 = 'workspace 3'
ctrl-4 = 'workspace 4'
ctrl-5 = 'workspace 5'
ctrl-6 = 'workspace 6'

ctrl-shift-1 = 'move-node-to-workspace 1'
ctrl-shift-2 = 'move-node-to-workspace 2'
ctrl-shift-3 = 'move-node-to-workspace 3'
ctrl-shift-4 = 'move-node-to-workspace 4'
ctrl-shift-5 = 'move-node-to-workspace 5'
ctrl-shift-6 = 'move-node-to-workspace 6'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-tab = 'workspace-back-and-forth'
alt-f = 'fullscreen'

alt-shift-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']


[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = ['layout tiling', 'move-node-to-workspace 1']
check-further-callbacks = false

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = ['layout tiling', 'move-node-to-workspace 2']
check-further-callbacks = false

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = ['layout tiling', 'move-node-to-workspace 3']
check-further-callbacks = false

[[on-window-detected]]
if.app-id = 'com.tencent.xinWeChat'
if.window-title-regex-substring = '^微信$|^WeChat$'
run = ['layout tiling', 'move-node-to-workspace 4']
check-further-callbacks = false

[[on-window-detected]]
if.app-id = 'com.tencent.xinWeChat'
run = 'layout floating'
check-further-callbacks = false

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = ['layout tiling', 'move-node-to-workspace 5']
check-further-callbacks = false

[[on-window-detected]]
if.workspace = 'ghost'
run = ['layout floating']
check-further-callbacks = false

[[on-window-detected]]
run = ['layout floating', 'move-node-to-workspace 6']
check-further-callbacks = false
